### ISSUE TITLE
CSS not connecting

### ISSUE THREAD

**Issue by kylemery** [kylemery/personal-website#1]
@thomasjbradley

My CSS is not connecting to my html after adding Jekyll. For the life of me I can't figure out why. I went through all the troubleshooting and I can't seem to see what it could be.

Thanks so much. 

Katrin

**Comment by thomasjbradley** [comment]
I can't see the code right now, it hasn't been committed and pushed since Oct. 12. Can you please commit and push so I can have a look?

**Comment by kylemery** [comment]
Hi Thomas, sorry, I forgot to push with the new Github app.

**Comment by kylemery** [comment]
I just did it.

**Comment by thomasjbradley** [comment]
Could be the frontmatter, look here:
https://github.com/kylemery/Personal-Website/blob/master/index.html#L1
There should be 3 dashes not 2.

**Comment by kylemery** [comment]
That was it! Woops! Thanks Thomas!
